### ISSUE TITLE
Windows extra dependencies

### ISSUE THREAD

**Issue by zefie** [theori-io/nrsc5#183]
The guide states you only need to copy libnrsc5.dll and nrsc5.exe, this is incorrect. Following your guide using the msys2-build script, the following need to be copied (all from the same bin folder):

libao-4.dll
libgcc_s_dw2-1.dll
libnrsc5.dll
librtlsdr.dll
libusb-1.0.dll
nrsc5.exe

Only then can nrsc5 run outside of the msys environment.

**Comment by awesie** [comment]
That's because the msys build script does not attempt to statically compile everything if the dependencies are already installed, unlike the cross compilation script, and you probably already have those dependencies installed.

I'm torn between updating the README to make this clear and updating the script to ignore the system libraries on the MSYS2 build.

**Comment by awesie** [comment]
The latest commit should change the MSYS2 build script to avoid using the system libraries and explicitly statically link.
