### ISSUE TITLE
Single iBOC sideband decoding? 

### ISSUE THREAD

**Issue by pclov3r** [theori-io/nrsc5#221]
So it appears that if a sideband is completely blocked or has horrible multipath NRSC5 will not decode any audio. Other hardware radios seem to be able to lock and decode with only a a good single iBOC sideband present. 

Not sure what the NRSC-5 spec says about this or if it should or shouldn't be supported.

I've some some people claim that with a station that only has 2 HD streams both sidebands contain duplicate information. For HD3 and 4 stations both need to be present. Not sure how true this is. 

Thanks!

**Comment by argilo** [comment]
One reason this doesn't currently work is that the synchronization code requires two particular reference subcarriers to be present, one in the lower sideband and one in the upper sideband:

https://github.com/theori-io/nrsc5/blob/17181bb604ede55e5be6fba372b4865cb1e0a5aa/src/sync.c#L226-L237

If one sideband is gone (or even if narrow-band noise knocks out one of those two specific subcarriers) then synchronization will fail.

Synchronization should be done in a more flexible way.

**Comment by argilo** [comment]
@pclov3r I've fixed this in #223.

> I've some some people claim that with a station that only has 2 HD streams both sidebands contain duplicate information. For HD3 and 4 stations both need to be present. Not sure how true this is.

The difference is that the P1 logical channel (which typically contains the HD1 & HD2 subchannels) uses a rate 2/5 error-correcting code (which can tolerate up to 60% of the data being missing), whereas the P3 logical channel (which typically contains the HD3 subchannel) uses a rate 1/2 error-correcting code (which can only tolerate 50% of the data being missing). A missing sideband knocks out 50% of the data, leaving the P3 logical channel on the fringe of decodability. Neither of my hardware HD Radio receivers can decode it, but nrsc5 with #223 can (albeit with the occasional audio packet lost due to a CRC error).

**Comment by pclov3r** [comment]
Thanks for the patch @argilo I'll give this a try later today if I can. 

Also, This patch will probably give a higher chance at decoding and for people using this for DXing conditions.
